# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protocol_protobuf/shaketoacc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protocol_protobuf/shaketoacc.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\"Protocol_protobuf/shaketoacc.proto\"4\n\nShakeToAcc\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x02(\x05\x12\x0c\n\x04port\x18\x03 \x02(\x05')
)




_SHAKETOACC = _descriptor.Descriptor(
  name='ShakeToAcc',
  full_name='ShakeToAcc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ShakeToAcc.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='ShakeToAcc.code', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ShakeToAcc.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['ShakeToAcc'] = _SHAKETOACC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShakeToAcc = _reflection.GeneratedProtocolMessageType('ShakeToAcc', (_message.Message,), {
  'DESCRIPTOR' : _SHAKETOACC,
  '__module__' : 'Protocol_protobuf.shaketoacc_pb2'
  # @@protoc_insertion_point(class_scope:ShakeToAcc)
  })
_sym_db.RegisterMessage(ShakeToAcc)


# @@protoc_insertion_point(module_scope)
