# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import emu_pb2 as emu__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook1.proto',
  package='protoc3.lian_xi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x61\x64\x64ressbook1.proto\x12\x0fprotoc3.lian_xi\x1a\temu.proto\"6\n\x0b\x41\x64\x64ressBook\x12\'\n\x06people\x18\x01 \x03(\x0b\x32\x17.protoc3.lian_xi.Person\"\xee\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x02\x12\x13\n\x0bwork_status\x18\x05 \x01(\x08\x12,\n\x06phones\x18\x06 \x03(\x0b\x32\x1c.protoc3.lian_xi.PhoneNumber\x12 \n\x04maps\x18\x07 \x03(\x0b\x32\x12.protoc3.MyMessage\x12,\n\x05hobby\x18\x08 \x03(\x0b\x32\x1d.protoc3.lian_xi.Person.Hobby\x1a\x19\n\x05Hobby\x12\x10\n\x08interest\x18\x01 \x01(\t\"G\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.protoc3.lian_xi.PhoneType*+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\x62\x06proto3')
  ,
  dependencies=[emu__pb2.DESCRIPTOR,])

_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='protoc3.lian_xi.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=420,
  serialized_end=463,
)
_sym_db.RegisterEnumDescriptor(_PHONETYPE)

PhoneType = enum_type_wrapper.EnumTypeWrapper(_PHONETYPE)
MOBILE = 0
HOME = 1
WORK = 2



_ADDRESSBOOK = _descriptor.Descriptor(
  name='AddressBook',
  full_name='protoc3.lian_xi.AddressBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='protoc3.lian_xi.AddressBook.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=104,
)


_PERSON_HOBBY = _descriptor.Descriptor(
  name='Hobby',
  full_name='protoc3.lian_xi.Person.Hobby',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interest', full_name='protoc3.lian_xi.Person.Hobby.interest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=345,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='protoc3.lian_xi.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protoc3.lian_xi.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='protoc3.lian_xi.Person.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='protoc3.lian_xi.Person.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='money', full_name='protoc3.lian_xi.Person.money', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='work_status', full_name='protoc3.lian_xi.Person.work_status', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phones', full_name='protoc3.lian_xi.Person.phones', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maps', full_name='protoc3.lian_xi.Person.maps', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hobby', full_name='protoc3.lian_xi.Person.hobby', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_HOBBY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=345,
)


_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='protoc3.lian_xi.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='protoc3.lian_xi.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protoc3.lian_xi.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=418,
)

_ADDRESSBOOK.fields_by_name['people'].message_type = _PERSON
_PERSON_HOBBY.containing_type = _PERSON
_PERSON.fields_by_name['phones'].message_type = _PHONENUMBER
_PERSON.fields_by_name['maps'].message_type = emu__pb2._MYMESSAGE
_PERSON.fields_by_name['hobby'].message_type = _PERSON_HOBBY
_PHONENUMBER.fields_by_name['type'].enum_type = _PHONETYPE
DESCRIPTOR.message_types_by_name['AddressBook'] = _ADDRESSBOOK
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['PhoneNumber'] = _PHONENUMBER
DESCRIPTOR.enum_types_by_name['PhoneType'] = _PHONETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressBook = _reflection.GeneratedProtocolMessageType('AddressBook', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSBOOK,
  '__module__' : 'addressbook1_pb2'
  # @@protoc_insertion_point(class_scope:protoc3.lian_xi.AddressBook)
  })
_sym_db.RegisterMessage(AddressBook)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'Hobby' : _reflection.GeneratedProtocolMessageType('Hobby', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_HOBBY,
    '__module__' : 'addressbook1_pb2'
    # @@protoc_insertion_point(class_scope:protoc3.lian_xi.Person.Hobby)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'addressbook1_pb2'
  # @@protoc_insertion_point(class_scope:protoc3.lian_xi.Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.Hobby)

PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
  'DESCRIPTOR' : _PHONENUMBER,
  '__module__' : 'addressbook1_pb2'
  # @@protoc_insertion_point(class_scope:protoc3.lian_xi.PhoneNumber)
  })
_sym_db.RegisterMessage(PhoneNumber)


# @@protoc_insertion_point(module_scope)
