# !/usr/bin/env python
# -*- coding: UTF-8 -*-
__author__ = 'liuzhaoyang'


from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import *
Base = declarative_base()


class t_baokam(Base):
    __tablename__ = 't_baokam'
    rid = Column(Integer, primary_key=True)
    s1 = Column(Integer, nullable=False,default=0)  # 1收集一部分,2收集完未领取奖励,3已领取奖励
    s2 = Column(Integer, nullable=False,default=0)
    s3 = Column(Integer, nullable=False,default=0)
    s4 = Column(Integer, nullable=False,default=0)
    s5 = Column(Integer, nullable=False,default=0)
    s6 = Column(Integer, nullable=False,default=0)
    s7 = Column(Integer, nullable=False,default=0)
    s8 = Column(Integer, nullable=False,default=0)
    s9 = Column(Integer, nullable=False,default=0)
    s10 = Column(Integer, nullable=False,default=0)
    s11 = Column(Integer, nullable=False,default=0)
    s12 = Column(Integer, nullable=False,default=0)
    s13 = Column(Integer, nullable=False,default=0)
    s14 = Column(Integer, nullable=False,default=0)
    s15 = Column(Integer, nullable=False,default=0)
    s16 = Column(Integer, nullable=False,default=0)
    s17 = Column(Integer, nullable=False,default=0)
    s18 = Column(Integer, nullable=False,default=0)
    s19 = Column(Integer, nullable=False,default=0)
    s20 = Column(Integer, nullable=False,default=0)
    s21 = Column(Integer, nullable=False,default=0)
    s22 = Column(Integer, nullable=False,default=0)
    s23 = Column(Integer, nullable=False,default=0)
    s24 = Column(Integer, nullable=False,default=0)
    s25 = Column(Integer, nullable=False,default=0)
    s26 = Column(Integer, nullable=False,default=0)
    s27 = Column(Integer, nullable=False,default=0)
    s28 = Column(Integer, nullable=False,default=0)
    s29 = Column(Integer, nullable=False,default=0)
    s30 = Column(Integer, nullable=False,default=0)
    s31 = Column(Integer, nullable=False,default=0)
    s32 = Column(Integer, nullable=False,default=0)
    s33 = Column(Integer, nullable=False,default=0)
    s34 = Column(Integer, nullable=False,default=0)
    s35 = Column(Integer, nullable=False,default=0)
    s36 = Column(Integer, nullable=False,default=0)
    s37 = Column(Integer, nullable=False,default=0)
    s38 = Column(Integer, nullable=False,default=0)
    s39 = Column(Integer, nullable=False,default=0)
    s40 = Column(Integer, nullable=False,default=0)
    s41 = Column(Integer, nullable=False,default=0)
    s42 = Column(Integer, nullable=False,default=0)
    s43 = Column(Integer, nullable=False,default=0)
    s44 = Column(Integer, nullable=False,default=0)
    s45 = Column(Integer, nullable=False,default=0)
    s46 = Column(Integer, nullable=False,default=0)
    s47 = Column(Integer, nullable=False,default=0)
    s48 = Column(Integer, nullable=False,default=0)
    s49 = Column(Integer, nullable=False,default=0)
    s50 = Column(Integer, nullable=False,default=0)
    s51 = Column(Integer, nullable=False,default=0)
    s52 = Column(Integer, nullable=False,default=0)
    s53 = Column(Integer, nullable=False,default=0)
    s54 = Column(Integer, nullable=False,default=0)
    s55 = Column(Integer, nullable=False,default=0)
    s56 = Column(Integer, nullable=False,default=0)
    s57 = Column(Integer, nullable=False,default=0)
    s58 = Column(Integer, nullable=False,default=0)
    s59 = Column(Integer, nullable=False,default=0)
    s60 = Column(Integer, nullable=False,default=0)
    s61 = Column(Integer, nullable=False,default=0)
    s62 = Column(Integer, nullable=False,default=0)
    s63 = Column(Integer, nullable=False,default=0)
    s64 = Column(Integer, nullable=False,default=0)
    s65 = Column(Integer, nullable=False,default=0)
    s66 = Column(Integer, nullable=False,default=0)
    s67 = Column(Integer, nullable=False,default=0)
    s68 = Column(Integer, nullable=False,default=0)
    s69 = Column(Integer, nullable=False,default=0)
    s70 = Column(Integer, nullable=False,default=0)
    s71 = Column(Integer, nullable=False,default=0)
    s72 = Column(Integer, nullable=False,default=0)
    s73 = Column(Integer, nullable=False,default=0)
    s74 = Column(Integer, nullable=False,default=0)
    s75 = Column(Integer, nullable=False,default=0)
    s76 = Column(Integer, nullable=False,default=0)
    s77 = Column(Integer, nullable=False,default=0)
    s78 = Column(Integer, nullable=False,default=0)
    s79 = Column(Integer, nullable=False,default=0)
    s80 = Column(Integer, nullable=False,default=0)
    s81 = Column(Integer, nullable=False,default=0)
    s82 = Column(Integer, nullable=False,default=0)
    s83 = Column(Integer, nullable=False,default=0)
    s84 = Column(Integer, nullable=False,default=0)
    s85 = Column(Integer, nullable=False,default=0)
    s86 = Column(Integer, nullable=False,default=0)
    s87 = Column(Integer, nullable=False,default=0)
    s88 = Column(Integer, nullable=False,default=0)
    s89 = Column(Integer, nullable=False,default=0)
    s90 = Column(Integer, nullable=False,default=0)
    s91 = Column(Integer, nullable=False,default=0)
    s92 = Column(Integer, nullable=False,default=0)
    s93 = Column(Integer, nullable=False,default=0)
    s94 = Column(Integer, nullable=False,default=0)
    s95 = Column(Integer, nullable=False,default=0)
    s96 = Column(Integer, nullable=False,default=0)
    s97 = Column(Integer, nullable=False,default=0)
    s98 = Column(Integer, nullable=False,default=0)
    s99 = Column(Integer, nullable=False,default=0)
    s100 = Column(Integer, nullable=False,default=0)

    @classmethod
    def new_from(cls, obj):
        new_obj = cls()
        for attr_name in cls._sa_class_manager.keys():
            if attr_name not in ['id', 'rid']:
                setattr(new_obj, attr_name, getattr(obj, attr_name))
        return new_obj