#!/usr/bin/env python
#-*- coding: UTF-8 -*-
__author__ = 'liuzhaoyang'

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import *
Base = declarative_base()


class t_october1st(Base):
    __tablename__ = 't_october1st'
    rid = Column(Integer, primary_key=True)
    t1 = Column(Enum("yes","no","get"), nullable=True, default="no") # 任务完成进度
    t2 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t3 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t4 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t5 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t6 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t7 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t8 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t9 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t10 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t11 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t12 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t13 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t14 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t15 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t16 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t17 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t18 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t19 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t20 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t21 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t22 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t23 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t24 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t25 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t26 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t27 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t28 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t29 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t30 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t31 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t32 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t33 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t34 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t35 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t36 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t37 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t38 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t39 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t40 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t41 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t42 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t43 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t44 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t45 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t46 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t47 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t48 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t49 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t50 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t51 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t52 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t53 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t54 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t55 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t56 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t57 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t58 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t59 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t60 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t61 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t62 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t63 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t64 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t65 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t66 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t67 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t68 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t69 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t70 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t71 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t72 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t73 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t74 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t75 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t76 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t77 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t78 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t79 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t80 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t81 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t82 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t83 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t84 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t85 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t86 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t87 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t88 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t89 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t90 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t91 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t92 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t93 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t94 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t95 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t96 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t97 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t98 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t99 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t100 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t101 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t102 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t103 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t104 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t105 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t106 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t107 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t108 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t109 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t110 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t111 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t112 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t113 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t114 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t115 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t116 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t117 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t118 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t119 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t120 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t121 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t122 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t123 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t124 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t125 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t126 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t127 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t128 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t129 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t130 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t131 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t132 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t133 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t134 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t135 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t136 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t137 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t138 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t139 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t140 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t141 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t142 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t143 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t144 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t145 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t146 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t147 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t148 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t149 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t150 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t151 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t152 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t153 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t154 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t155 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t156 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t157 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t158 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t159 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t160 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t161 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t162 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t163 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t164 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t165 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t166 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t167 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t168 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t169 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t170 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t171 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t172 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t173 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t174 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t175 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t176 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t177 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t178 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t179 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t180 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t181 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t182 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t183 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t184 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t185 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t186 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t187 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t188 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t189 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t190 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t191 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t192 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t193 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t194 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t195 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t196 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t197 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t198 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t199 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t200 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t201 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t202 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t203 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t204 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t205 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t206 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t207 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t208 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t209 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t210 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t211 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t212 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t213 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t214 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t215 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t216 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t217 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t218 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t219 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t220 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t221 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t222 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t223 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t224 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t225 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t226 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t227 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t228 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t229 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t230 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t231 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t232 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t233 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t234 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t235 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t236 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t237 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t238 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t239 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t240 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t241 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t242 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t243 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t244 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t245 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t246 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t247 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t248 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t249 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t250 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t251 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t252 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t253 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t254 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t255 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t256 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t257 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t258 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t259 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t260 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t261 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t262 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t263 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t264 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t265 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t266 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t267 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t268 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t269 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t270 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t271 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t272 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t273 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t274 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t275 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t276 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t277 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t278 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t279 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t280 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t281 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t282 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t283 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t284 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t285 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t286 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t287 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t288 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t289 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t290 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t291 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t292 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t293 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t294 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t295 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t296 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t297 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t298 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t299 = Column(Enum("yes","no","get"), nullable=True, default="no")
    t300 = Column(Enum("yes","no","get"), nullable=True, default="no")
    c1 = Column(Integer, nullable=True, default=0) # 累计充值钱数
    c2 = Column(Integer, nullable=True, default=0) # 普通副本胜利次数
    c3 = Column(Integer, nullable=True, default=0) # 名将副本胜利次数
    c4 = Column(Integer, nullable=True, default=0) # 灭神殿挑战次数 （挑战第一关，活动开启不在第一关时+1）
    c5 = Column(Integer, nullable=True, default=0) # 银币副本胜利次数
    c6 = Column(Integer, nullable=True, default=0) # 王的男人胜利次数
    c7 = Column(Integer, nullable=True, default=0) # 蓬莱仙洞挑战次数 （第一步挑战次数）
    c8 = Column(Integer, nullable=True, default=0) # 过关斩将挑战次数
    c9 = Column(Integer, nullable=True, default=0) # 夺宝挑战次数
    c10 = Column(Integer, nullable=True, default=0) # 竞技场挑战次数
    c11 = Column(Integer, nullable=True, default=0) # 好友副本挑战次数
    c12 = Column(Integer, nullable=True, default=0) # 锻造石副本胜利次数
    c13 = Column(Integer, nullable=True, default=0) # 经验副本胜利次数
    c14 = Column(Integer, nullable=True, default=0) # 银币猎命次数
    c15 = Column(Integer, nullable=True, default=0) # 元宝猎命次数
    c16 = Column(Integer, nullable=True, default=0) # 冠军试炼挑战次数 第一次
    c17 = Column(Integer, nullable=True, default=0)
    c18 = Column(Integer, nullable=True, default=0)
    c19 = Column(Integer, nullable=True, default=0)
    c20 = Column(Integer, nullable=True, default=0)
    c21 = Column(Integer, nullable=True, default=0)
    c22 = Column(Integer, nullable=True, default=0)
    c23 = Column(Integer, nullable=True, default=0)
    c24 = Column(Integer, nullable=True, default=0)
    c25 = Column(Integer, nullable=True, default=0)
    c26 = Column(Integer, nullable=True, default=0)
    c27 = Column(Integer, nullable=True, default=0)
    c28 = Column(Integer, nullable=True, default=0)
    c29 = Column(Integer, nullable=True, default=0)
    c30 = Column(Integer, nullable=True, default=0)

    @classmethod
    def new_from(cls, obj):
        new_obj = cls()
        for attr_name in cls._sa_class_manager.keys():
            if attr_name not in ['id', 'rid']:
                setattr(new_obj, attr_name, getattr(obj, attr_name))
        return new_obj


