# -*- coding: utf-8 -*-

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import *
Base = declarative_base()


class t_patrol(Base):
    __tablename__ = "t_patrol"
    rid = Column(Integer, primary_key=True)
    mid = Column(Integer, primary_key=True)

    is_attack = Column(Boolean, nullable=False, default=False)

    gid = Column(Integer, nullable=True, default=None)          # 占领的武将id
    consume_cfg_id = Column(Integer, nullable=False, default=0) # 消费时间配置id
    event_cfg_id = Column(Integer, nullable=False, default=0)   # 随机事件配置id

    gfid = Column(Integer, nullable=True, default=None)         # 产出武将碎片id
    gfcount = Column(Integer, nullable=False, default=0)        # 产出武将碎片个数

    ts = Column(TIMESTAMP, nullable=True, default=None)         # 巡山开始时间
    income_count = Column(Integer, nullable=False, default=0)   # 收益次数
    income_double = Column(Boolean, nullable=False, default=False)   # 收益翻倍

    c1 = Column(Integer, nullable=False, default=0) # 收益战报配置id
    i1 = Column(Integer, nullable=False, default=0) # 收益掉落配置id
    c2 = Column(Integer, nullable=False, default=0)
    i2 = Column(Integer, nullable=False, default=0)
    c3 = Column(Integer, nullable=False, default=0)
    i3 = Column(Integer, nullable=False, default=0)
    c4 = Column(Integer, nullable=False, default=0)
    i4 = Column(Integer, nullable=False, default=0)
    c5 = Column(Integer, nullable=False, default=0)
    i5 = Column(Integer, nullable=False, default=0)
    c6 = Column(Integer, nullable=False, default=0)
    i6 = Column(Integer, nullable=False, default=0)
    c7 = Column(Integer, nullable=False, default=0)
    i7 = Column(Integer, nullable=False, default=0)
    c8 = Column(Integer, nullable=False, default=0)
    i8 = Column(Integer, nullable=False, default=0)
    c9 = Column(Integer, nullable=False, default=0)
    i9 = Column(Integer, nullable=False, default=0)
    c10 = Column(Integer, nullable=False, default=0)
    i10 = Column(Integer, nullable=False, default=0)
    c11 = Column(Integer, nullable=False, default=0)
    i11 = Column(Integer, nullable=False, default=0)
    c12 = Column(Integer, nullable=False, default=0)
    i12 = Column(Integer, nullable=False, default=0)
    c13 = Column(Integer, nullable=False, default=0)
    i13 = Column(Integer, nullable=False, default=0)
    c14 = Column(Integer, nullable=False, default=0)
    i14 = Column(Integer, nullable=False, default=0)
    c15 = Column(Integer, nullable=False, default=0)
    i15 = Column(Integer, nullable=False, default=0)
    c16 = Column(Integer, nullable=False, default=0)
    i16 = Column(Integer, nullable=False, default=0)
    c17 = Column(Integer, nullable=False, default=0)
    i17 = Column(Integer, nullable=False, default=0)
    c18 = Column(Integer, nullable=False, default=0)
    i18 = Column(Integer, nullable=False, default=0)
    c19 = Column(Integer, nullable=False, default=0)
    i19 = Column(Integer, nullable=False, default=0)
    c20 = Column(Integer, nullable=False, default=0)
    i20 = Column(Integer, nullable=False, default=0)
    c21 = Column(Integer, nullable=False, default=0)
    i21 = Column(Integer, nullable=False, default=0)
    c22 = Column(Integer, nullable=False, default=0)
    i22 = Column(Integer, nullable=False, default=0)
    c23 = Column(Integer, nullable=False, default=0)
    i23 = Column(Integer, nullable=False, default=0)
    c24 = Column(Integer, nullable=False, default=0)
    i24 = Column(Integer, nullable=False, default=0)
    c25 = Column(Integer, nullable=False, default=0)
    i25 = Column(Integer, nullable=False, default=0)
    c26 = Column(Integer, nullable=False, default=0)
    i26 = Column(Integer, nullable=False, default=0)
    c27 = Column(Integer, nullable=False, default=0)
    i27 = Column(Integer, nullable=False, default=0)
    c28 = Column(Integer, nullable=False, default=0)
    i28 = Column(Integer, nullable=False, default=0)
    c29 = Column(Integer, nullable=False, default=0)
    i29 = Column(Integer, nullable=False, default=0)
    c30 = Column(Integer, nullable=False, default=0)
    i30 = Column(Integer, nullable=False, default=0)
    c31 = Column(Integer, nullable=False, default=0)
    i31 = Column(Integer, nullable=False, default=0)
    c32 = Column(Integer, nullable=False, default=0)
    i32 = Column(Integer, nullable=False, default=0)
    c33 = Column(Integer, nullable=False, default=0)
    i33 = Column(Integer, nullable=False, default=0)
    c34 = Column(Integer, nullable=False, default=0)
    i34 = Column(Integer, nullable=False, default=0)
    c35 = Column(Integer, nullable=False, default=0)
    i35 = Column(Integer, nullable=False, default=0)
    c36 = Column(Integer, nullable=False, default=0)
    i36 = Column(Integer, nullable=False, default=0)
    c37 = Column(Integer, nullable=False, default=0)
    i37 = Column(Integer, nullable=False, default=0)
    c38 = Column(Integer, nullable=False, default=0)
    i38 = Column(Integer, nullable=False, default=0)
    c39 = Column(Integer, nullable=False, default=0)
    i39 = Column(Integer, nullable=False, default=0)
    c40 = Column(Integer, nullable=False, default=0)
    i40 = Column(Integer, nullable=False, default=0)
    c41 = Column(Integer, nullable=False, default=0)
    i41 = Column(Integer, nullable=False, default=0)
    c42 = Column(Integer, nullable=False, default=0)
    i42 = Column(Integer, nullable=False, default=0)
    c43 = Column(Integer, nullable=False, default=0)
    i43 = Column(Integer, nullable=False, default=0)
    c44 = Column(Integer, nullable=False, default=0)
    i44 = Column(Integer, nullable=False, default=0)
    c45 = Column(Integer, nullable=False, default=0)
    i45 = Column(Integer, nullable=False, default=0)
    c46 = Column(Integer, nullable=False, default=0)
    i46 = Column(Integer, nullable=False, default=0)
    c47 = Column(Integer, nullable=False, default=0)
    i47 = Column(Integer, nullable=False, default=0)
    c48 = Column(Integer, nullable=False, default=0)
    i48 = Column(Integer, nullable=False, default=0)
    c49 = Column(Integer, nullable=False, default=0)
    i49 = Column(Integer, nullable=False, default=0)
    c50 = Column(Integer, nullable=False, default=0)
    i50 = Column(Integer, nullable=False, default=0)
    c51 = Column(Integer, nullable=False, default=0)
    i51 = Column(Integer, nullable=False, default=0)
    c52 = Column(Integer, nullable=False, default=0)
    i52 = Column(Integer, nullable=False, default=0)
    c53 = Column(Integer, nullable=False, default=0)
    i53 = Column(Integer, nullable=False, default=0)
    c54 = Column(Integer, nullable=False, default=0)
    i54 = Column(Integer, nullable=False, default=0)
    c55 = Column(Integer, nullable=False, default=0)
    i55 = Column(Integer, nullable=False, default=0)
    c56 = Column(Integer, nullable=False, default=0)
    i56 = Column(Integer, nullable=False, default=0)
    c57 = Column(Integer, nullable=False, default=0)
    i57 = Column(Integer, nullable=False, default=0)
    c58 = Column(Integer, nullable=False, default=0)
    i58 = Column(Integer, nullable=False, default=0)
    c59 = Column(Integer, nullable=False, default=0)
    i59 = Column(Integer, nullable=False, default=0)
    c60 = Column(Integer, nullable=False, default=0)
    i60 = Column(Integer, nullable=False, default=0)
    c61 = Column(Integer, nullable=False, default=0)
    i61 = Column(Integer, nullable=False, default=0)
    c62 = Column(Integer, nullable=False, default=0)
    i62 = Column(Integer, nullable=False, default=0)
    c63 = Column(Integer, nullable=False, default=0)
    i63 = Column(Integer, nullable=False, default=0)
    c64 = Column(Integer, nullable=False, default=0)
    i64 = Column(Integer, nullable=False, default=0)
    c65 = Column(Integer, nullable=False, default=0)
    i65 = Column(Integer, nullable=False, default=0)
    c66 = Column(Integer, nullable=False, default=0)
    i66 = Column(Integer, nullable=False, default=0)
    c67 = Column(Integer, nullable=False, default=0)
    i67 = Column(Integer, nullable=False, default=0)
    c68 = Column(Integer, nullable=False, default=0)
    i68 = Column(Integer, nullable=False, default=0)
    c69 = Column(Integer, nullable=False, default=0)
    i69 = Column(Integer, nullable=False, default=0)
    c70 = Column(Integer, nullable=False, default=0)
    i70 = Column(Integer, nullable=False, default=0)
    c71 = Column(Integer, nullable=False, default=0)
    i71 = Column(Integer, nullable=False, default=0)
    c72 = Column(Integer, nullable=False, default=0)
    i72 = Column(Integer, nullable=False, default=0)
    c73 = Column(Integer, nullable=False, default=0)
    i73 = Column(Integer, nullable=False, default=0)
    c74 = Column(Integer, nullable=False, default=0)
    i74 = Column(Integer, nullable=False, default=0)
    c75 = Column(Integer, nullable=False, default=0)
    i75 = Column(Integer, nullable=False, default=0)
    c76 = Column(Integer, nullable=False, default=0)
    i76 = Column(Integer, nullable=False, default=0)
    c77 = Column(Integer, nullable=False, default=0)
    i77 = Column(Integer, nullable=False, default=0)
    c78 = Column(Integer, nullable=False, default=0)
    i78 = Column(Integer, nullable=False, default=0)
    c79 = Column(Integer, nullable=False, default=0)
    i79 = Column(Integer, nullable=False, default=0)
    c80 = Column(Integer, nullable=False, default=0)
    i80 = Column(Integer, nullable=False, default=0)
    c81 = Column(Integer, nullable=False, default=0)
    i81 = Column(Integer, nullable=False, default=0)
    c82 = Column(Integer, nullable=False, default=0)
    i82 = Column(Integer, nullable=False, default=0)
    c83 = Column(Integer, nullable=False, default=0)
    i83 = Column(Integer, nullable=False, default=0)
    c84 = Column(Integer, nullable=False, default=0)
    i84 = Column(Integer, nullable=False, default=0)
    c85 = Column(Integer, nullable=False, default=0)
    i85 = Column(Integer, nullable=False, default=0)
    c86 = Column(Integer, nullable=False, default=0)
    i86 = Column(Integer, nullable=False, default=0)
    c87 = Column(Integer, nullable=False, default=0)
    i87 = Column(Integer, nullable=False, default=0)
    c88 = Column(Integer, nullable=False, default=0)
    i88 = Column(Integer, nullable=False, default=0)
    c89 = Column(Integer, nullable=False, default=0)
    i89 = Column(Integer, nullable=False, default=0)
    c90 = Column(Integer, nullable=False, default=0)
    i90 = Column(Integer, nullable=False, default=0)
    c91 = Column(Integer, nullable=False, default=0)
    i91 = Column(Integer, nullable=False, default=0)
    c92 = Column(Integer, nullable=False, default=0)
    i92 = Column(Integer, nullable=False, default=0)
    c93 = Column(Integer, nullable=False, default=0)
    i93 = Column(Integer, nullable=False, default=0)
    c94 = Column(Integer, nullable=False, default=0)
    i94 = Column(Integer, nullable=False, default=0)
    c95 = Column(Integer, nullable=False, default=0)
    i95 = Column(Integer, nullable=False, default=0)
    c96 = Column(Integer, nullable=False, default=0)
    i96 = Column(Integer, nullable=False, default=0)
    c97 = Column(Integer, nullable=False, default=0)
    i97 = Column(Integer, nullable=False, default=0)
    c98 = Column(Integer, nullable=False, default=0)
    i98 = Column(Integer, nullable=False, default=0)
    c99 = Column(Integer, nullable=False, default=0)
    i99 = Column(Integer, nullable=False, default=0)
    c100 = Column(Integer, nullable=False, default=0)
    i100 = Column(Integer, nullable=False, default=0)

    @classmethod
    def new_from(cls, obj):
        new_obj = cls()
        for attr_name in cls._sa_class_manager.keys():
            if attr_name not in ['rid']:
                setattr(new_obj, attr_name, getattr(obj, attr_name))
        return new_obj
