# -*- coding: utf-8 -*-

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import *
Base = declarative_base()


class t_world_war_role(Base):
    __tablename__ = 't_world_war_role'
    id = Column(Integer, primary_key=True, autoincrement=True)
    server_id = Column(Integer, nullable=False)
    rid = Column(Integer, nullable=False)
    name = Column(String, nullable=False)
    level = Column(Integer, nullable=False)
    power = Column(Integer, nullable=False, default=0)

    rank1 = Column(Integer, nullable=False, default=0)
    rank2 = Column(Integer, nullable=False, default=0)
    rank3 = Column(Integer, nullable=False, default=0)
    rank4 = Column(Integer, nullable=False, default=0)
    rank5 = Column(Integer, nullable=False, default=0)
    rank6 = Column(Integer, nullable=False, default=0)
    rank7 = Column(Integer, nullable=False, default=0)
    rank8 = Column(Integer, nullable=False, default=0)
    rank9 = Column(Integer, nullable=False, default=0)
    rank10 = Column(Integer, nullable=False, default=0)
    rank11 = Column(Integer, nullable=False, default=0)
    rank12 = Column(Integer, nullable=False, default=0)
    rank13 = Column(Integer, nullable=False, default=0)
    rank14 = Column(Integer, nullable=False, default=0)
    rank15 = Column(Integer, nullable=False, default=0)
    rank16 = Column(Integer, nullable=False, default=0)
    rank17 = Column(Integer, nullable=False, default=0)
    rank18 = Column(Integer, nullable=False, default=0)
    rank19 = Column(Integer, nullable=False, default=0)
    rank20 = Column(Integer, nullable=False, default=0)
    rank21 = Column(Integer, nullable=False, default=0)
    rank22 = Column(Integer, nullable=False, default=0)
    rank23 = Column(Integer, nullable=False, default=0)
    rank24 = Column(Integer, nullable=False, default=0)
    rank25 = Column(Integer, nullable=False, default=0)
    rank26 = Column(Integer, nullable=False, default=0)
    rank27 = Column(Integer, nullable=False, default=0)
    rank28 = Column(Integer, nullable=False, default=0)
    rank29 = Column(Integer, nullable=False, default=0)
    rank30 = Column(Integer, nullable=False, default=0)
    rank31 = Column(Integer, nullable=False, default=0)
    rank32 = Column(Integer, nullable=False, default=0)
    rank33 = Column(Integer, nullable=False, default=0)
    rank34 = Column(Integer, nullable=False, default=0)
    rank35 = Column(Integer, nullable=False, default=0)
    rank36 = Column(Integer, nullable=False, default=0)
    rank37 = Column(Integer, nullable=False, default=0)
    rank38 = Column(Integer, nullable=False, default=0)
    rank39 = Column(Integer, nullable=False, default=0)
    rank40 = Column(Integer, nullable=False, default=0)
    rank41 = Column(Integer, nullable=False, default=0)
    rank42 = Column(Integer, nullable=False, default=0)
    rank43 = Column(Integer, nullable=False, default=0)
    rank44 = Column(Integer, nullable=False, default=0)
    rank45 = Column(Integer, nullable=False, default=0)
    rank46 = Column(Integer, nullable=False, default=0)
    rank47 = Column(Integer, nullable=False, default=0)
    rank48 = Column(Integer, nullable=False, default=0)
    rank49 = Column(Integer, nullable=False, default=0)
    rank50 = Column(Integer, nullable=False, default=0)
    rank51 = Column(Integer, nullable=False, default=0)
    rank52 = Column(Integer, nullable=False, default=0)
    rank53 = Column(Integer, nullable=False, default=0)
    rank54 = Column(Integer, nullable=False, default=0)
    rank55 = Column(Integer, nullable=False, default=0)
    rank56 = Column(Integer, nullable=False, default=0)
    rank57 = Column(Integer, nullable=False, default=0)
    rank58 = Column(Integer, nullable=False, default=0)
    rank59 = Column(Integer, nullable=False, default=0)
    rank60 = Column(Integer, nullable=False, default=0)

    @classmethod
    def new_from(cls, obj):
        new_obj = cls()
        for attr_name in cls._sa_class_manager.keys():
            if attr_name not in []:
                setattr(new_obj, attr_name, getattr(obj, attr_name))
        return new_obj
