#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Auther: houguangdong
# @Time: 2020/6/10

CLIENT_SYS_ANDROID = 'Android'
CLIENT_SYS_IOS = 'IOS'
CLIENT_SYS_WINPC = 'Winpc'
CLIENT_SYS_H5 = 'H5'
CLIENT_SYS_MACOS = 'MAC'

PHONETYPE_CHINAMOBILE_STR = "chinaMobile"
PHONETYPE_CHINAUNION_STR = "chinaUnion"
PHONETYPE_CHINATELECOM_STR = "chinaTelecom"
PHONETYPE_OTHER_STR = "other"

PHONETYPE_CHINAMOBILE = 0
PHONETYPE_CHINAUNION = 1
PHONETYPE_CHINATELECOM = 2
PHONETYPE_OTHER = 3